image: registry.sensetime.com/zoetrope/pytorch:1.7.0-cuda11.0-cudnn8-ffmpeg4-pytorch3d-mmcv

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - gcc --version
  - python --version
  - pip --version
  - nvcc --version
  - python -c "import torch; print(torch.__version__)"
  - ffmpeg -version
  - export http_proxy=http://172.16.1.135:3128/
  - export https_proxy=http://172.16.1.135:3128/
  - export HTTP_PROXY=http://172.16.1.135:3128/
  - export HTTPS_PROXY=http://172.16.1.135:3128/

linting:
  stage: linting
  script:
    - pre-commit install
    - pre-commit run --all-files --verbose
    - echo "Docstring coverage results:"
    - interrogate -vinmMI -f 40 mmhuman3d/

test:
  stage: test
  tags:
    - gpu
  script:
    - nvidia-smi
    - echo "Start building..."
    - pip install -e .
    - python -c "import mmhuman3d; print(mmhuman3d.__version__)"
    - unset http_proxy
    - unset https_proxy
    - unset HTTP_PROXY
    - unset HTTPS_PROXY
    - mkdir mmhuman3d_download
    - cd mmhuman3d_download
    - wget -q http://10.4.11.59:18080/mmhuman3d.tar
    - tar -xvf mmhuman3d.tar
    - cd ..
    - cp -r mmhuman3d_download/mmhuman3d/* ./
    - rm -rf mmhuman3d_download
    - echo "Start testing..."
    - coverage run --source mmhuman3d -m pytest tests/
    - coverage report -m
